blank_issues_enabled: false
contact_links:
  - name: ğŸ“ â€‹â€‹Typo or Grammatical Mistake
    url: https://github.com/Zyphaex/enjindex/pulls
    about: Please submit a pull request instead of reporting it as an issue.
  - name: ğŸ¤ â€‹Community
    url: https://discord.com/invite/XfZHVfPr9C
    about: Join my community Discord server.